### PR TITLE
Feature/support customized java

### PR DESCRIPTION
**Pull request by vettal-wu**
This PR provide an interface support customized java command to start jvm. If ${PLATFORM}/bin/customized.java.path exists, java cmd defined in this file will be used to start jvm, else default java cmd will be used.

Solve: #98

### CODE REVIEW

**Comment by shakeelmohamed** [comment]
Can we open a new PR against `develop`? The changes seem fine to me

**Comment by vettal-wu** [comment]
Thanks, I have change this PR against develop.

**Comment by shakeelmohamed** [comment]
@vettal-wu please resolve the merge conflicts 😄

**Comment by vettal-wu** [comment]
@shakeelmohamed Conflicts have been resolved and I have uploaded the recompiled exe file. Please review and test it. Thank you!

**Comment by shakeelmohamed** [comment]
Thanks @vettal-wu!

**Pull request merged**
