### PR TITLE
Fix bug of Value.toDate(string value) is not thread safe.

### PR DESCRIPTION
**Pull request by brucewu-fly**
Fix bug of Value.toDate(string value) is not thread safe.

### CODE REVIEW

**Comment by brucewu-fly** [comment]
#108

**Comment by brucewu-fly** [comment]
The reasons why Date toDate(String value) is not thread safe are:
The static member variables dateFormat, datePattern will be initialized many times when multiple threads invoke this method.
The method parse() of SimpleDateFormat is not thread safe.

In general, there are three ways to solve this problem.
Introduce synchronized.  Date toDate(String value) -> synchronized Date toDate(String value)
Use eager instantiation for dateFormat and datePattern. Put SimpleDateFormat[] dateFormat in ThreadLocal.
Use eager instantiation for dateFormat and datePattern. Introduce third party libraries JODA time and use DateTimeFormat.forPattern to format time.

I prefer option 1 since it has minimal impact on the original code. In most cases we don't have multithreaded access so it won't cause thread context switch.

**Comment by brucewu-fly** [comment]
The CI output

`travis:
BUILD FAILED
/home/travis/build/splunk/splunk-sdk-java/build.xml:358: Problem: failed to create task or type junit
Cause: the class org.apache.tools.ant.taskdefs.optional.junit.JUnitTask was not found.
        This looks like one of Ant's optional components.
Action: Check that the appropriate optional JAR exists in
        -/usr/share/ant/lib
        -/home/travis/.ant/lib
        -a directory added on the command line with the -lib argument
Do not panic, this is a common problem.
The commonest cause is a missing JAR.
This is not a bug; it is a configuration problem
`

**Comment by shakeelmohamed** [comment]
The build failure here is very strange, I've sent an email to Travis CI support

**Comment by shakeelmohamed** [comment]
I've fixed some Travis CI configuration on the develop branch, merge it into your branch and the tests should run properly again

**Pull request merged**
