### PR TITLE
Feature/support updated field in entity

### LINKED ISSUE #103: Entity object does not contain the "updated" field
When we send splunkd a rest api to get the entity, there exists a field "updated" in the response which means the last modified time of this entity. This value may be useful in some cases. For example, some apps want to sort the objects according to the last modified time.

But in java sdk, this field is skipped after parsing the response to an entity, and we can't get the value. I think it's necessary for sdk to provide this field in entity object.

### PR DESCRIPTION
**Pull request by vettal-wu**
resolve #103

### CODE REVIEW

**Comment by vettal-wu** [comment]
resolve #104

**Comment by shakeelmohamed** [comment]
Should we parse and return a `Date` object?

**Comment by vergnes** [comment]
+1 for returning a Date

**Comment by shakeelmohamed** [comment]
LGTM, thanks guys

**Pull request merged**
