### PR TITLE
- Fixed error message parsing in HttpException.create()

### PR DESCRIPTION
**Pull request by VampKyivUA**
Fixed failure parsing XML response from Splunk in HttpException:create()

### CODE REVIEW

**Comment by shakeelmohamed** [comment]
Hi @VampKyivUA,

This seems like a reasonable change. Can you add a test for the opposite case, when we are able to successfully parse the XML document?

Could you also please fill out the contributor agreement: http://www.splunk.com/goto/individualcontributions

Thanks

**Comment by VampKyivUA** [comment]
Hi @shakeelmohamed,

Thanks for the comments!
I've signed contributor's agreement and added test case for not-xml response.

Could you please also review the latest commit 9affb49?
Silent option is added to Xml.parse(InputStream).
Reason for doing so is that in some cases (like HttpException.create()) SAXException is "swallowed", while parse errors are still written to **stderr** by default error handler. 
So, it makes it difficult to track where those error messages came from (since exception is "swallowed").

This change affects only HttpException class, in other cases (Job, JobCollection etc) SAX exception is rethrown, therefore, I think there is no need to suppress error messages from an XML parser.

**Comment by shakeelmohamed** [comment]
@VampKyivUA overall, this looks fine.

I just left a comment on the test suite you added - fix that and I'll accept the changes. I like that you made sure your changes were non-invasive with a sane default. Thanks for filling out the contributor's agreement, we've received it.

Thanks for doing this work! :smile:

**Comment by VampKyivUA** [comment]
@shakeelmohamed thanks for the comments!
I've marked ```setUp()``` with ```@BeforeClass``` this should do the same thing. Just want to keep actual test "logic" as simple as possible, moving all the preparation steps into appropriate method.

**Comment by shakeelmohamed** [comment]
@VampKyivUA that works too. We're not planning a release at this time, so it may be a while before this makes it out the door.

**Comment by adamryman** [comment]
We just released v1.5.0 with these changes. Thanks for your help!

**Pull request merged**
