### PR TITLE
Fix wrong receiver endpoint

### LINKED ISSUE #101: Namespace breaks Index.submit
If you set a namespace in your session, you can't Index.submit.

I have a test framework which allows for test cases to submit data to Splunk, then ensure it's parsed correctly - but they share the same session.

```
// Create session
ServiceArgs loginArgs = new ServiceArgs();
loginArgs.setApp("testapp");
... set user/pass ...
service = Service.connect(loginArgs);

// Retrieve the index for the data
Index myIndex = service.getIndexes().get( "main" );

// Specify  values to apply to the event
Args eventArgs = new Args();
eventArgs.put("sourcetype", sourcetype);
eventArgs.put("host", "local");

// Submit an event over HTTP
myIndex.submit(eventArgs, data);
```

Error
```
com.splunk.HttpException: HTTP 404 -- Not Found
        at com.splunk.HttpException.create(HttpException.java:84)
        at com.splunk.HttpService.send(HttpService.java:452)
        at com.splunk.Service.send(Service.java:1293)
        at com.splunk.Receiver.submit(Receiver.java:169)
        at com.splunk.Index.submit(Index.java:1097)
```

Easy workaround is to have a seperate session for reading / writing. Maybe this is by design?

### PR DESCRIPTION
**Pull request by liketic**
Resolves #101  😄

### CODE REVIEW

**Comment by shakeelmohamed** [comment]
Let's add a test that tries to submit an event with a namespaced service. See [IndexTest. tryTestSubmitOne()](https://github.com/splunk/splunk-sdk-java/blob/6cd33941cff36a31686e1a3cc6e36f2e4ee39bab/tests/com/splunk/IndexTest.java#L423)

**Comment by liketic** [comment]
@shakeelmohamed A new test added, pls review again.

**Comment by liketic** [comment]
@shakeelmohamed Seems like the build env is broken. 😢

**Comment by liketic** [comment]
@shakeelmohamed Any updates?

**Comment by tdhellmann** [comment]
Hi @liketic - I've filed a ticket on our end to get this review prioritized. Thanks again for the PR and sorry for the delay!

**Comment by shakeelmohamed** [comment]
Closed in favor of #118

**Pull request closed without merging**
