### PR TITLE
Add getters for embed properties

### PR DESCRIPTION
**Pull request by sodle**
Allow us to retrieved whether or not the search is enabled for embedding, and the auth token for embedding if it is.

https://answers.splunk.com/answers/477391/can-i-get-the-iframe-embed-url-for-a-report-via-th.html

### CODE REVIEW

**Comment by shakeelmohamed** [comment]
Thanks for the PR @sodle, can you fill out the [contribution agreement](http://dev.splunk.com/goto/individualcontributions)?

**Comment by sodle** [comment]
Done, thanks.

**Comment by shakeelmohamed** [comment]
Thanks @sodle, we've merged your change with some test coverage to the `develop` branch. How soon do you need a release with your changes?

**Comment by sodle** [comment]
No hurry. For my current project, I can just do an ant build with my changes and use that.

**Pull request closed without merging**
